[build]
  publish = "static"
  command = "echo 'No build needed'"

# Explicitly disable Python build
[build.environment]
  NODE_ENV = "production"
  PYTHON_VERSION = "3.9"  # Use a version Netlify supports

# Or better yet, force Node.js environment
[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200