[build]
  publish = "static"
  command = "echo 'No build needed'"

[build.environment]
  NODE_ENV = "production"
  PYTHON_VERSION = "3.9"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
